image: ubuntu

environment:
  matrix:
  - nodejs_version: 'Stable'
  - nodejs_version: '8'

init:
  git config --global core.autocrlf true

install:
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run test

build: off